import os
import csv
import chromadb
import anthropic
import time
from sentence_transformers import SentenceTransformer
from dotenv import load_dotenv

load_dotenv()

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
CHROMA_DIR = "data/chroma_db"
EVAL_CSV = "data/eval_set/questions_fixed.csv"
RESULTS_DIR = "data/results"
os.makedirs(RESULTS_DIR, exist_ok=True)

def load_eval_set():
    questions = []
    with open(EVAL_CSV, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            questions.append(row)
    return questions

def retrieve(collection, model, query, top_k=5):
    query_embedding = model.encode([query]).tolist()
    results = collection.query(
        query_embeddings=query_embedding,
        n_results=top_k
    )
    return results["documents"][0], results["metadatas"][0]

def generate_answer(question, context_chunks):
    context = "\n\n---\n\n".join(context_chunks)
    prompt = f"""You are an aviation safety analyst. Answer the following question using only the context provided below. If the answer cannot be found in the context, say "I cannot determine this from the provided context."

Context:
{context}

Question: {question}

Provide a concise, direct answer."""

    response = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=300,
        messages=[{"role": "user", "content": prompt}]
    )
    return response.content[0].text.strip()

def judge_answer(question, generated_answer, ground_truth, context_chunks):
    context = "\n\n---\n\n".join(context_chunks)
    prompt = f"""You are an expert evaluator assessing the quality of answers generated by a RAG system.

Evaluate the generated answer on two dimensions:

1. FAITHFULNESS (0-3): Is the generated answer supported by the provided context?
   0 = Answer contradicts or ignores the context entirely
   1 = Answer partially supported but contains unsupported claims
   2 = Answer mostly supported with minor extrapolation
   3 = Answer fully supported by the context

2. CORRECTNESS (0-3): Does the generated answer match the ground truth answer?
   0 = Completely incorrect or missing key information
   1 = Partially correct but missing significant details
   2 = Mostly correct with minor omissions or differences
   3 = Fully correct and complete

Context provided to the RAG system:
{context}

Question: {question}

Ground truth answer: {ground_truth}

Generated answer: {generated_answer}

Return only a JSON object with exactly these four fields:
- faithfulness: integer 0-3
- correctness: integer 0-3
- faithfulness_reason: one sentence explanation
- correctness_reason: one sentence explanation

No preamble, no markdown backticks. All four fields are required."""

    response = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=200,
        messages=[{"role": "user", "content": prompt}]
    )

    import json
    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]

    parsed = json.loads(raw.strip())

    # Ensure all fields present with fallback defaults
    return {
        "faithfulness": parsed.get("faithfulness", 0),
        "correctness": parsed.get("correctness", 0),
        "faithfulness_reason": parsed.get("faithfulness_reason", "Not provided"),
        "correctness_reason": parsed.get("correctness_reason", "Not provided")
    }

def run_judge(collection_name, top_k=5):
    print(f"\nRunning judge evaluation: {collection_name} | top_k={top_k}")

    output_file = os.path.join(RESULTS_DIR, f"{collection_name}_k{top_k}_judge.csv")
    fieldnames = [
        "collection", "source_doc", "difficulty", "question",
        "ground_truth", "generated_answer", "faithfulness",
        "correctness", "faithfulness_reason", "correctness_reason"
    ]

    # Load already completed questions to skip them
    completed_questions = set()
    if os.path.exists(output_file):
        with open(output_file, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                completed_questions.add(row["question"])
        print(f"  Resuming — {len(completed_questions)} questions already completed")

    model = SentenceTransformer("all-MiniLM-L6-v2")
    chroma_client = chromadb.PersistentClient(path=CHROMA_DIR)
    collection = chroma_client.get_collection(collection_name)
    questions = load_eval_set()

    # Open in append mode so completed results are preserved
    write_header = not os.path.exists(output_file)
    f_out = open(output_file, "a", newline="", encoding="utf-8")
    writer = csv.DictWriter(f_out, fieldnames=fieldnames)
    if write_header:
        writer.writeheader()

    completed = len(completed_questions)
    for i, q in enumerate(questions):
        if q["question"] in completed_questions:
            continue

        try:
            chunks, metadatas = retrieve(collection, model, q["question"], top_k=top_k)
            generated = generate_answer(q["question"], chunks)
            scores = judge_answer(q["question"], generated, q["answer"], chunks)

            row = {
                "collection": collection_name,
                "source_doc": q["source_doc"],
                "difficulty": q["difficulty"],
                "question": q["question"],
                "ground_truth": q["answer"],
                "generated_answer": generated,
                "faithfulness": scores["faithfulness"],
                "correctness": scores["correctness"],
                "faithfulness_reason": scores["faithfulness_reason"],
                "correctness_reason": scores["correctness_reason"]
            }
            writer.writerow(row)
            f_out.flush()  # Write to disk immediately
            completed += 1

            if completed % 10 == 0:
                print(f"  {completed}/{len(questions)} evaluated")

        except Exception as e:
            print(f"  Error on question {i+1}: {e} — skipping")

        time.sleep(2)

    f_out.close()

    # Load full results for summary
    results = []
    with open(output_file, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            results.append(row)

    total = len(results)
    avg_faithfulness = sum(int(r["faithfulness"]) for r in results) / total
    avg_correctness = sum(int(r["correctness"]) for r in results) / total

    print(f"\n  Avg Faithfulness: {avg_faithfulness:.2f}/3")
    print(f"  Avg Correctness:  {avg_correctness:.2f}/3")

    for diff in ["easy", "medium", "hard"]:
        subset = [r for r in results if r["difficulty"] == diff]
        f = sum(int(r["faithfulness"]) for r in subset) / len(subset)
        c = sum(int(r["correctness"]) for r in subset) / len(subset)
        print(f"  {diff}: Faithfulness={f:.2f}, Correctness={c:.2f}")

    print(f"\n  Results saved to {output_file}")
    return avg_faithfulness, avg_correctness

if __name__ == "__main__":
    run_judge("atsb_cs500_co50", top_k=5)